version: "3"

services:
  # Reference link: https://hub.docker.com/r/_/redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  
  # Reference link: https://hub.docker.com/_/mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
  
  # Reference link: https://hub.docker.com/_/neo4j
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment: 
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687

  # Reference link: https://hub.docker.com/_/cassandra
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
  

  # Reference link: https://store.docker.com/community/images/bigtop/sandbox
  # And, the user guide can be found at https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=70256303.
  hbase:
    image: bigtop/sandbox:1.2.1-ubuntu-16.04-hdfs_hbase
    container_name: hbase
    ports:
      - 50070:50070
      - 16010:10610
  
